# Stage 1
ARG ASPNET_IMAGE_TAG=8.0.0-bookworm-slim
ARG DOTNET_SDK_IMAGE_TAG=8.0
ARG NODEJS_IMAGE_TAG=18-bullseye

FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_IMAGE_TAG} AS publish

WORKDIR /build

ENV DEBIAN_FRONTEND=noninteractive

COPY Dfe.ManageFreeSchoolProjects/. .

RUN dotnet restore Dfe.ManageFreeSchoolProjects
RUN dotnet build Dfe.ManageFreeSchoolProjects -c Release
RUN dotnet publish Dfe.ManageFreeSchoolProjects -c Release -o /app --no-build

COPY ./script/web-docker-entrypoint.sh /app/docker-entrypoint.sh

# Stage 2 - Build assets
FROM node:${NODEJS_IMAGE_TAG} as build
COPY --from=publish /app /app
WORKDIR /app/wwwroot
RUN npm install
RUN npm run build

# Stage 3 - Final
FROM "mcr.microsoft.com/dotnet/aspnet:${ASPNET_IMAGE_TAG}" AS final
LABEL org.opencontainers.image.source=https://github.com/DFE-Digital/manage-free-school-projects

ARG COMMIT_SHA
ENV ASPNETCORE_HTTP_PORTS=80

RUN apt-get update
RUN apt-get install unixodbc curl gnupg jq -y
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install msodbcsql18 mssql-tools18 -y

COPY --from=build /app /app
WORKDIR /app
RUN chmod +x ./docker-entrypoint.sh

EXPOSE 80/tcp
