using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dfe.ManageFreeSchoolProjects.Data.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "KPI",
                columns: table => new
                {
                    p_rid = table.Column<string>(type: "varchar(11)", unicode: false, maxLength: 11, nullable: true),
                    RID = table.Column<string>(type: "varchar(11)", unicode: false, maxLength: 11, nullable: true),
                    ProjectStatusCurrentfreeschoolname = table.Column<string>(name: "Project Status.Current free school name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusHasthefreeschoolchangeditsname = table.Column<string>(name: "Project Status.Has the free school changed its name?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusPreviousfreeschoolname = table.Column<string>(name: "Project Status.Previous free school name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusProjectstatus = table.Column<string>(name: "Project Status.Project status", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusFreeschoolsapplicationnumber = table.Column<string>(name: "Project Status.Free schools application number", type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    ProjectStatusProjectID = table.Column<string>(name: "Project Status.Project ID", type: "varchar(25)", unicode: false, maxLength: 25, nullable: true),
                    ProjectStatusFreeschoolapplicationwave = table.Column<string>(name: "Project Status.Free school application wave", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateofapplicationifoutsidewave = table.Column<DateTime>(name: "Project Status.Date of application if outside wave", type: "date", nullable: true),
                    ProjectStatusRealisticyearofopening = table.Column<string>(name: "Project Status.Realistic year of opening", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateofentryintopreopening = table.Column<DateTime>(name: "Project Status.Date of entry into pre-opening", type: "date", nullable: true),
                    ProjectStatusTrustspreferredyearofopening = table.Column<string>(name: "Project Status.Trusts preferred year of opening", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusProvisionalopeningdateagreedwithtrust = table.Column<DateTime>(name: "Project Status.Provisional opening date agreed with trust", type: "date", nullable: true),
                    ProjectStatusActualopeningdate = table.Column<DateTime>(name: "Project Status.Actual opening date", type: "date", nullable: true),
                    ProjectStatusPlannedmovedatetopermanentsite = table.Column<DateTime>(name: "Project Status.Planned move date to permanent site", type: "date", nullable: true),
                    ProjectStatusHastheprojectbeendeferred = table.Column<string>(name: "Project Status.Has the project been deferred?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateoffirstdeferral = table.Column<DateTime>(name: "Project Status.Date of first deferral", type: "date", nullable: true),
                    ProjectStatusPrimaryreasonforfirstdeferral = table.Column<string>(name: "Project Status.Primary reason for first deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusReasonforsitedeferral = table.Column<string>(name: "Project Status.Reason for site deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusCommentaryforfirstdeferral = table.Column<string>(name: "Project Status.Commentary for first deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusNewopeningdatefollowingfirstdeferral = table.Column<DateTime>(name: "Project Status.New opening date following first deferral", type: "date", nullable: true),
                    ProjectStatusHasprojectbeendeferredforasecondtime = table.Column<string>(name: "Project Status.Has project been deferred for a second time?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateofseconddeferral = table.Column<DateTime>(name: "Project Status.Date of second deferral", type: "date", nullable: true),
                    ProjectStatusPrimaryreasonforseconddeferral = table.Column<string>(name: "Project Status.Primary reason for second deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusKP05_Reasonforsitedeferral = table.Column<string>(name: "Project Status.KP05_Reason for site deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusCommentaryforseconddeferral = table.Column<string>(name: "Project Status.Commentary for second deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusNewopeningdatefollowingseconddeferral = table.Column<DateTime>(name: "Project Status.New opening date following second deferral", type: "date", nullable: true),
                    ProjectStatusHasprojectbeendeferredforathirdtime = table.Column<string>(name: "Project Status.Has project been deferred for a third time?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateofthirddeferral = table.Column<DateTime>(name: "Project Status.Date of third deferral", type: "date", nullable: true),
                    ProjectStatusPrimaryreasonforthirddeferral = table.Column<string>(name: "Project Status.Primary reason for third deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusKP06_Reasonforsitedeferral = table.Column<string>(name: "Project Status.KP06_Reason for site deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusCommentaryforthirddeferral = table.Column<string>(name: "Project Status.Commentary for third deferral", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusNewopeningdatefollowingthirddeferral = table.Column<DateTime>(name: "Project Status.New opening date following third deferral", type: "date", nullable: true),
                    ProjectStatusHasprojectbeenwithdrawn = table.Column<string>(name: "Project Status.Has project been withdrawn?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDatewithdrawn = table.Column<DateTime>(name: "Project Status.Date withdrawn", type: "date", nullable: true),
                    ProjectStatusPrimaryreasonforwithdrawal = table.Column<string>(name: "Project Status.Primary reason for withdrawal", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusReasonforsitewithdrawal = table.Column<string>(name: "Project Status.Reason for site withdrawal", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusCommentaryforwithdrawal = table.Column<string>(name: "Project Status.Commentary for withdrawal", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusHasprojectbeencancelled = table.Column<string>(name: "Project Status.Has project been cancelled?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDatecancelled = table.Column<DateTime>(name: "Project Status.Date cancelled", type: "date", nullable: true),
                    ProjectStatusPrimaryreasonforcancellation = table.Column<string>(name: "Project Status.Primary reason for cancellation", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusReasonforsitecancellation = table.Column<string>(name: "Project Status.Reason for site cancellation", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusCommentaryforcancellation = table.Column<string>(name: "Project Status.Commentary for cancellation", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusDateclosed = table.Column<DateTime>(name: "Project Status.Date closed", type: "date", nullable: true),
                    ProjectStatusActualdateofopeninginpermanentaccommodation = table.Column<DateTime>(name: "Project Status.Actual date of opening in permanent accommodation", type: "date", nullable: true),
                    ProjectStatusActualdateofopeningintemporaryaccommodation = table.Column<DateTime>(name: "Project Status.Actual date of opening in temporary accommodation", type: "date", nullable: true),
                    ProjectStatusFreeschoolpenportrait = table.Column<string>(name: "Project Status.Free school pen portrait", type: "varchar(max)", unicode: false, nullable: true),
                    ProjectStatusURNwhengivenone = table.Column<string>(name: "Project Status.URN (when given one)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ProjectStatusRebrokeredURN = table.Column<string>(name: "Project Status.Rebrokered URN", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsLAESTABwhengivenone = table.Column<string>(name: "School Details.LAESTAB (when given one)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsLocalauthority = table.Column<string>(name: "School Details.Local authority", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    Localauthority = table.Column<string>(name: "Local authority", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsLocalauthoritycontrol = table.Column<string>(name: "School Details.Local authority control", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsDistrict = table.Column<string>(name: "School Details.District", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsAEACatagory = table.Column<string>(name: "School Details.AEA Catagory", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsStartoftermdate = table.Column<DateTime>(name: "School Details.Start of term date", type: "date", nullable: true),
                    SchoolDetailsDeprivationdecline = table.Column<string>(name: "School Details.Deprivation decline", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsNEETinLA = table.Column<string>(name: "School Details.% NEET in LA", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsRSCregion = table.Column<string>(name: "School Details.RSC region", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsGeographicalRegion = table.Column<string>(name: "School Details.Geographical Region", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsEFATerritory = table.Column<string>(name: "School Details.EFA Territory", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsConstituency = table.Column<string>(name: "School Details.Constituency", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsConstituencyMP = table.Column<string>(name: "School Details.Constituency MP", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsPoliticalparty = table.Column<string>(name: "School Details.Political party", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsNumberofformsofentry = table.Column<string>(name: "School Details.Number of forms of entry", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSchooltypemainstreamAPetc = table.Column<string>(name: "School Details.School type (mainstream, AP etc)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSchoolphaseprimarysecondary = table.Column<string>(name: "School Details.School phase (primary, secondary)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsAgerange = table.Column<string>(name: "School Details.Age range", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsGender = table.Column<string>(name: "School Details.Gender", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsResidentialorboardingprovision = table.Column<string>(name: "School Details.Residential or boarding provision", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsDetailsofresidentialboardingprovision = table.Column<string>(name: "School Details.Details of residential/boarding provision", type: "varchar(max)", unicode: false, nullable: true),
                    SchoolDetailsNursery = table.Column<string>(name: "School Details.Nursery", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSixthform = table.Column<string>(name: "School Details.Sixth form", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSixthformtype = table.Column<string>(name: "School Details.Sixth form type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsIndependentconverter = table.Column<string>(name: "School Details.Independent converter", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSpecialistResourceProvision = table.Column<string>(name: "School Details.Specialist Resource Provision", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSizeofGoverningBody = table.Column<string>(name: "School Details.Size of Governing Body", type: "varchar(2)", unicode: false, maxLength: 2, nullable: true),
                    SchoolDetailsFaithstatus = table.Column<string>(name: "School Details.Faith status", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsFaithtype = table.Column<string>(name: "School Details.Faith type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsPleasespecifyotherfaithtype = table.Column<string>(name: "School Details.Please specify other faith type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSpecialism = table.Column<string>(name: "School Details.Specialism", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsDistinguishingfeatures = table.Column<string>(name: "School Details.Distinguishing features", type: "varchar(max)", unicode: false, nullable: true),
                    SchoolDetailsEmployersponsorsUTCsSSonly = table.Column<string>(name: "School Details.Employer sponsors - UTCs/SS only", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsUniversitySponsor = table.Column<string>(name: "School Details.University Sponsor", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsEmployerPartners = table.Column<string>(name: "School Details.Employer Partners", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsOtherPartners = table.Column<string>(name: "School Details.Other Partners", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsTypeofproposergroup = table.Column<string>(name: "School Details.Type of proposer group", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsPleasespecifyothertypeofproposergroup = table.Column<string>(name: "School Details.Please specify other type of proposer group", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsLeadsponsorID = table.Column<string>(name: "School Details.Lead sponsor ID", type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    SchoolDetailsLeadsponsorname = table.Column<string>(name: "School Details.Lead sponsor name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsSponsortype = table.Column<string>(name: "School Details.Sponsor type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsTrustID = table.Column<string>(name: "School Details.Trust ID", type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    SchoolDetailsTrustname = table.Column<string>(name: "School Details.Trust name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    SchoolDetailsTrusttype = table.Column<string>(name: "School Details.Trust type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedSchoolinplanningareaofbasicneedassessment = table.Column<string>(name: "Basic Need.School in planning area of basic need (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedKP02_Planningareacode = table.Column<string>(name: "Basic Need.KP02_Planning area code", type: "varchar(8)", unicode: false, maxLength: 8, nullable: true),
                    BasicNeedSchoolinplanningareaofbasicneedsecondaryassessment = table.Column<string>(name: "Basic Need.School in planning area of basic need - secondary (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedSchoolinlocalareawithashortfallofplacessecondaryassessment = table.Column<string>(name: "Basic Need.School in local area with a shortfall of places - secondary (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedYearofprojectedneedsecondaryassessment = table.Column<string>(name: "Basic Need.Year of projected need - secondary (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedPlanningareacodesecondaryassessment = table.Column<string>(name: "Basic Need.Planning area code - secondary (assessment)", type: "varchar(8)", unicode: false, maxLength: 8, nullable: true),
                    BasicNeedAdditionalevidenceofneedsecondaryassessment = table.Column<string>(name: "Basic Need.Additional evidence of need - secondary (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedSchoolinplanningareaofbasicneed = table.Column<string>(name: "Basic Need.School in planning area of basic need", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedSchoolinlocalareawithashortfallofplacesinlocalarea = table.Column<string>(name: "Basic Need.School in local area with a shortfall of places in local area", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedYearofSCAPsurvey = table.Column<string>(name: "Basic Need.Year of SCAP survey", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedShortfallofplacesinlocalareaallyeargroupsinSCAPyear4 = table.Column<string>(name: "Basic Need.Shortfall of places in local area (all year groups in SCAP year +4)", type: "varchar(4)", unicode: false, maxLength: 4, nullable: true),
                    BasicNeedPercentageshortfallinlocalareaallyeargroupsinSCAPyear4 = table.Column<string>(name: "Basic Need.Percentage shortfall in local area (all year groups in SCAP year +4)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedShortfallofplacesinlocalareayearofopeningallyeargroups = table.Column<string>(name: "Basic Need.Shortfall of places in local area — year of opening (all year groups)", type: "varchar(4)", unicode: false, maxLength: 4, nullable: true),
                    BasicNeedPercentageshortfallinlocalareayearofopeningallyeargroups = table.Column<string>(name: "Basic Need.Percentage shortfall in local area — year of opening (all year groups)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedKP04_Planningareacode = table.Column<string>(name: "Basic Need.KP04_Planning area code", type: "varchar(8)", unicode: false, maxLength: 8, nullable: true),
                    BasicNeedAdditionalevidenceofneed = table.Column<string>(name: "Basic Need.Additional evidence of need", type: "varchar(1000)", unicode: false, maxLength: 1000, nullable: true),
                    BasicNeedSchoolinplanningareaofbasicneedsecondary = table.Column<string>(name: "Basic Need.School in planning area of basic need - secondary", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedSchoolinlocalareawithashortfallofplacesinlocalareasecondary = table.Column<string>(name: "Basic Need.School in local area with a shortfall of places in local area - secondary", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedYearofSCAPsurveysecondary = table.Column<string>(name: "Basic Need.Year of SCAP survey - secondary", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedShortfallofplacesinlocalareaallyeargroupsinSCAPyear4secondary = table.Column<string>(name: "Basic Need.Shortfall of places in local area (all year groups in SCAP year +4) - secondary", type: "varchar(4)", unicode: false, maxLength: 4, nullable: true),
                    BasicNeedPercentageshortfallinlocalareaallyeargroupsinSCAPyear4secondary = table.Column<string>(name: "Basic Need.Percentage shortfall in local area (all year groups in SCAP year +4) - secondary", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedShortfallofplacesinlocalareayearofopeningallyeargroupssecondary = table.Column<string>(name: "Basic Need.Shortfall of places in local area - year of opening (all year groups) - secondary", type: "varchar(4)", unicode: false, maxLength: 4, nullable: true),
                    BasicNeedPercentageshortfallinlocalareayearofopeningallyeargroupssecondary = table.Column<string>(name: "Basic Need.Percentage shortfall in local area - year of opening (all year groups) - secondary", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    BasicNeedPlanningareacodesecondary = table.Column<string>(name: "Basic Need.Planning area code - secondary", type: "varchar(8)", unicode: false, maxLength: 8, nullable: true),
                    BasicNeedAdditionalevidenceofneedsecondary = table.Column<string>(name: "Basic Need.Additional evidence of need - secondary", type: "varchar(999)", unicode: false, maxLength: 999, nullable: true),
                    KeyContactsSchooladdress = table.Column<string>(name: "Key Contacts.School address", type: "varchar(max)", unicode: false, nullable: true),
                    KeyContactsPostcode = table.Column<string>(name: "Key Contacts.Postcode", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPostCodeforMapping = table.Column<string>(name: "Key Contacts.PostCode for Mapping", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLeadproposername = table.Column<string>(name: "Key Contacts.Lead proposer name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLeadproposerphone = table.Column<string>(name: "Key Contacts.Lead proposer phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLeadproposeremail = table.Column<string>(name: "Key Contacts.Lead proposer email ", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsAddressofleadproposer = table.Column<string>(name: "Key Contacts.Address of lead proposer", type: "varchar(max)", unicode: false, nullable: true),
                    KeyContactsLocalauthoritycontactpresumptionproject = table.Column<string>(name: "Key Contacts.Local authority contact (presumption project)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPrincipalDesignateName = table.Column<string>(name: "Key Contacts.Principal Designate Name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPrincipalDesignatephone = table.Column<string>(name: "Key Contacts.Principal Designate phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPrincipalDesignateemail = table.Column<string>(name: "Key Contacts.Principal Designate email", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsSeniorExecutiveLeadername = table.Column<string>(name: "Key Contacts.Senior Executive Leader name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsSeniorExecutiveLeaderphone = table.Column<string>(name: "Key Contacts.Senior Executive Leader phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsSeniorExecutiveLeaderemail = table.Column<string>(name: "Key Contacts.Senior Executive Leader email", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofGovernorsname = table.Column<string>(name: "Key Contacts.Chair of Governors name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofGovernorsphone = table.Column<string>(name: "Key Contacts.Chair of Governors phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofGovernorsemail = table.Column<string>(name: "Key Contacts.Chair of Governors email", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofgovernorsMAT = table.Column<string>(name: "Key Contacts.Chair of governors MAT", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofgovernorsMATphone = table.Column<string>(name: "Key Contacts.Chair of governors MAT phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsChairofgovernorsMATemail = table.Column<string>(name: "Key Contacts.Chair of governors MAT email", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsTrustsICTleadcontact = table.Column<string>(name: "Key Contacts.Trust's ICT lead contact", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsTrustsICTleadcontactphone = table.Column<string>(name: "Key Contacts.Trust's ICT lead contact phone", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsTrustsICTleadcontactemail = table.Column<string>(name: "Key Contacts.Trust's ICT lead contact email", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFSGassessmentlead = table.Column<string>(name: "Key Contacts.FSG assessment lead", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsAssessmentteamleader = table.Column<string>(name: "Key Contacts.Assessment team leader", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsInterviewchair = table.Column<string>(name: "Key Contacts.Interview chair", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFSGleadcontact = table.Column<string>(name: "Key Contacts.FSG lead contact", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFSGteamleader = table.Column<string>(name: "Key Contacts.FSG team leader", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFSGGrade6 = table.Column<string>(name: "Key Contacts.FSG Grade 6", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFACapitalprojectmanager = table.Column<string>(name: "Key Contacts.ESFA Capital project manager", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFACapitalprojectmanagerfirm = table.Column<string>(name: "Key Contacts.ESFA Capital project manager firm", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFACapitalprojectdirector = table.Column<string>(name: "Key Contacts.ESFA Capital project director", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFACapitalHeadofRegion = table.Column<string>(name: "Key Contacts.ESFA Capital Head of Region", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFAacademiessenioradviser = table.Column<string>(name: "Key Contacts.ESFA academies senior adviser", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFALinkOfficer = table.Column<string>(name: "Key Contacts.ESFA Link Officer", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsEducationadviserassessment = table.Column<string>(name: "Key Contacts.Education adviser (assessment)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsEducationadviserpreopening = table.Column<string>(name: "Key Contacts.Education adviser (pre-opening)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsNamedcontactonceschoolisopen = table.Column<string>(name: "Key Contacts.Named contact once school is open", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsEAonceschoolisopen = table.Column<string>(name: "Key Contacts.EA once school is open", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsICTadviser = table.Column<string>(name: "Key Contacts.ICT adviser", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFApropertylead = table.Column<string>(name: "Key Contacts.ESFA property lead", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLocatEDacquisitionmanager = table.Column<string>(name: "Key Contacts.LocatED acquisition manager", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFAregionalpropertylead = table.Column<string>(name: "Key Contacts.ESFA regional property lead", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLegalmanager = table.Column<string>(name: "Key Contacts.Legal manager", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsCommercialManager = table.Column<string>(name: "Key Contacts.Commercial Manager", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPropertyfirmdealing = table.Column<string>(name: "Key Contacts.Property firm dealing", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPropertyadviserallocated = table.Column<string>(name: "Key Contacts.Property adviser allocated", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsAllocatedlawfirm = table.Column<string>(name: "Key Contacts.Allocated law firm", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFrameworkplanningconsultant = table.Column<string>(name: "Key Contacts.Framework planning consultant", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFrameworkplanningfirm = table.Column<string>(name: "Key Contacts.Framework planning firm", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsFrameworkplanningfirmother = table.Column<string>(name: "Key Contacts.Framework planning firm – other", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPlanningAdviser = table.Column<string>(name: "Key Contacts.Planning Adviser", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsPropertydocumentrepositorylink = table.Column<string>(name: "Key Contacts.Property document repository link", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsESFAtechnicaladviser = table.Column<string>(name: "Key Contacts.ESFA technical adviser", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsStrategicdesignadviser = table.Column<string>(name: "Key Contacts.Strategic design adviser", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsTechnicaladvisoryfirm = table.Column<string>(name: "Key Contacts.Technical advisory firm", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KeyContactsLegalfirm = table.Column<string>(name: "Key Contacts.Legal firm", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    CommunicationsMediapenportrait = table.Column<string>(name: "Communications.Media pen portrait", type: "varchar(max)", unicode: false, nullable: true),
                    CommunicationsCurrentlinestotake = table.Column<string>(name: "Communications.Current lines to take", type: "varchar(max)", unicode: false, nullable: true),
                    CommunicationsArchivedlinestotake = table.Column<string>(name: "Communications.Archived lines to take", type: "varchar(max)", unicode: false, nullable: true),
                    ContingencyPlanningRDDSiteContingencyRAG = table.Column<string>(name: "Contingency Planning.RDD Site Contingency RAG", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningRDDRationale = table.Column<string>(name: "Contingency Planning.RDD Rationale", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningIfOtherwhyforRandAexplainanythingbeingexploredornextsteps = table.Column<string>(name: "Contingency Planning.If 'Other', why? (for R and A, explain anything being explored or next steps)", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningEssentialthatitisdeliveredforSeptemberorcurrentscheduleddateintheRealisticYearofOpening = table.Column<string>(name: "Contingency Planning.Essential that it is delivered for September (or current scheduled date) in the Realistic Year of Opening?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningIfYeswhy = table.Column<string>(name: "Contingency Planning.If ‘Yes’, why?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningIfOtherwhy = table.Column<string>(name: "Contingency Planning.If 'Other', why?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningBackupField = table.Column<string>(name: "Contingency Planning.Back-up Field", type: "varchar(max)", unicode: false, nullable: true),
                    ContingencyPlanningFSCDeliverabilityAssessment = table.Column<string>(name: "Contingency Planning.FSC Deliverability Assessment", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningFSCDeliverabilityComment = table.Column<string>(name: "Contingency Planning.FSC Deliverability Comment", type: "varchar(max)", unicode: false, nullable: true),
                    ContingencyPlanningSiteshutdown = table.Column<string>(name: "Contingency Planning.Site shutdown", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningCantempsbeextended = table.Column<string>(name: "Contingency Planning.Can temps be extended?", type: "varchar(1000)", unicode: false, maxLength: 1000, nullable: true),
                    ContingencyPlanningHowlongcantempsbeextended = table.Column<string>(name: "Contingency Planning.How long can temps be extended?", type: "varchar(1000)", unicode: false, maxLength: 1000, nullable: true),
                    ContingencyPlanningCancurrentcohortremaininschool = table.Column<string>(name: "Contingency Planning.Can current cohort remain in school?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningCanschooltakeonanothercohort = table.Column<string>(name: "Contingency Planning.Can school take on another cohort?", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningHowmanystudentswillneedalternativearrangements = table.Column<string>(name: "Contingency Planning.How many students will need alternative arrangements?", type: "varchar(1000)", unicode: false, maxLength: 1000, nullable: true),
                    ContingencyPlanningProjectedlengthofdelaytoproject = table.Column<string>(name: "Contingency Planning.Projected length of delay to project", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ContingencyPlanningExtrainformation = table.Column<string>(name: "Contingency Planning.Extra information", type: "varchar(max)", unicode: false, nullable: true),
                    LeadsponsorID = table.Column<string>(name: "Lead sponsor ID", type: "varchar(7)", unicode: false, maxLength: 7, nullable: true),
                    Leadsponsorname = table.Column<string>(name: "Lead sponsor name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    TrustID = table.Column<string>(name: "Trust ID", type: "varchar(7)", unicode: false, maxLength: 7, nullable: true),
                    Trustname = table.Column<string>(name: "Trust name", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    Trusttype = table.Column<string>(name: "Trust type", type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    FS_Type = table.Column<string>(type: "varchar(14)", unicode: false, maxLength: 14, nullable: false),
                    FS_Type_1 = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: false),
                    SponsorUnitProjects = table.Column<string>(name: "Sponsor Unit Projects", type: "varchar(39)", unicode: false, maxLength: 39, nullable: false),
                    MATUnitProjects = table.Column<string>(name: "MAT Unit Projects", type: "varchar(32)", unicode: false, maxLength: 32, nullable: false),
                    RATProvisionalopeningdateagreedwithtrust = table.Column<DateTime>(name: "RAT Provisional opening date agreed with trust", type: "date", nullable: true),
                    AprilIndicator = table.Column<string>(name: "April Indicator", type: "varchar(10)", unicode: false, maxLength: 10, nullable: false),
                    Wave = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: false),
                    RYOO_WD = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    UpperStatus = table.Column<string>(name: "Upper Status", type: "varchar(10)", unicode: false, maxLength: 10, nullable: false)
                },
                constraints: table =>
                {
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "KPI");
        }
    }
}
